[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT MAIN_APP:app"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "gcc", "pkg-config", "poppler_utils", "libffi", "openssl"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip setuptools wheel",
    ". /opt/venv/bin/activate && pip install -r requirements-docker.txt"
]
